In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/Placement/sentiment_analysis.csv")
data.head()

   id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...

In [ ]:
data.isnull().sum()

id       0
label    0
tweet    0
dtype: int64

In [ ]:
plt.rcParams['text.usetex'] = False

In [ ]:
data['tweet'] = data['tweet'].str.replace('$', r'\$', regex=False)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
x=data['tweet']
y=data['label']

In [ ]:
vectorizer = CountVectorizer()
x_vectorized = vectorizer.fit_transform(x)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    x_vectorized,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print(y_pred)

[0 0 0 ... 1 1 0]

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.8907828282828283

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.93      0.93      1152
           1       0.80      0.80      0.80       432

    accuracy                           0.89      1584
   macro avg       0.86      0.86      0.86      1584
weighted avg       0.89      0.89      0.89      1584

In [ ]:
new_tweet = ["I really love this product"]
new_tweet_vectorized = vectorizer.transform(new_tweet)
prediction = model.predict(new_tweet_vectorized)
print(prediction)

[0]

In [ ]:
if prediction[0] == 1:
    print("\nPositive Sentiment")
else:
    print("\nNegative Sentiment")

Negative Sentiment